<?php

declare(strict_types=1);

namespace Msamgan\Lact\Commands;

use Exception;
use Illuminate\Console\Command;
use Illuminate\Routing\Route;
use Msamgan\Lact\Concerns\CommonFunctions;
use Msamgan\Lact\Handlers\ContentHandler;
use Msamgan\Lact\Handlers\ControllerHandler;
use Msamgan\Lact\Handlers\FileHandler;
use Msamgan\Lact\Handlers\UrlHandler;
use ReflectionException;

class LactCommand extends Command
{
    use CommonFunctions;

    public $signature = 'lact:run';

    /**
     * It performs the following tasks:
     * - Clears the existing routes file generated by Lact.
     * - Parses controller methods that use a specific Action attribute and builds route strings for them.
     * - Deletes the previously generated actions directory to ensure a clean slate.
     * - Iterates through all action URLs, processes each route by HTTP method and generates corresponding JavaScript methods.
     * - Ensures the generated routes and methods are appended to the appropriate files.
     *
     * Use this command to automate the generation of routes and associated frontend methods
     * for dynamic or static actions based on your application's URL structure.
     */
    public $description = 'Processes and builds actions for registered URLs in the application';

    /**
     * @throws ReflectionException
     * @throws Exception
     */
    public function handle(UrlHandler $urlHandler, FileHandler $fileHandler, ContentHandler $contentHandler, ControllerHandler $controllerHandler): int
    {
        $fileHandler->emptyLactRoutesFile();
        // this here process controller methods which are uses Action Attribute.
        $this->processRoutes(
            routes: $contentHandler->createRouteString(routeMeta: $controllerHandler->processController()),
            fileHandler: $fileHandler
        );

        // removing the actions' dir.
        $fileHandler->removeDirectoryRecursively();

        foreach ($urlHandler->actionUrls() as $route) {
            foreach ($route->methods as $method) {
                if ($method === 'HEAD') {
                    continue;
                }

                $this->process(urlHandler: $urlHandler, fileHandler: $fileHandler, contentHandler: $contentHandler, route: $route, method: $method);
            }
        }

        return self::SUCCESS;
    }

    private function process(
        UrlHandler $urlHandler, FileHandler $fileHandler, ContentHandler $contentHandler, Route $route, string $method
    ): void {
        $extraction = $urlHandler->extractNames(route: $route);
        $fileHandler->appendToFileWithEmptyLine(
            filePath: $fileHandler->ensureJsFileExists(fileName: $extraction['fileName'], filePath: implode('/', $extraction['pathArray'])),
            content: $contentHandler->createMethodString(method: strtolower($method), replacers: [
                'routeName' => $route->getName(),
                'methodName' => $extraction['methodName'],
            ])
        );
    }

    private function processRoutes(array $routes, FileHandler $fileHandler): void
    {
        foreach ($routes as $route) {
            $fileHandler->appendToFileWithEmptyLine(
                filePath: $this->currentBasePath('routes/lact.php'),
                content: $route
            );
        }
    }
}
